# Crear etiqueta RPG
POST http://localhost:3000/admin-tags/post
content-type: application/json

{
    "id": 1,
    "name": "RPG"
}

######
# Crear etiqueta Shooter
POST http://localhost:3000/admin-tags/post
content-type: application/json

{
    "id": 2,
    "name": "Shooter"
}

######
# Obtener todas las etiquetas
GET http://localhost:3000/admin-tags/get

######
# Obtener la etiqueta 1
GET http://localhost:3000/admin-tags/get/1

######
# Actualizar la etiqueta 1
PUT http://localhost:3000/admin-tags/put/1
Content-Type: application/json

{
  "name": "Adventure"
}

######
# Eliminar la etiqueta 1
DELETE http://localhost:3000/admin-tags/delete/1
    

####

#Subir Videojuego
POST http://localhost:3000/admin-videogames/post
Content-Type: application/json

{
    "titulo": "Rat game 3",
    "portada": {"tipoImagen": "image/jpeg"},
    "imagepath": "Add path",
    "sinopsis": "It's a game about rats",
    "usuario": "ratman",
    "juegoZip":{"tipoArchivo": "application/zip"},
    "filepath": "Add path"
}

####

#Get videojuego
GET http://localhost:3000/admin-videogames/get
Content-Type: application/json

####

#Borrar videojuego
DELETE http://localhost:3000/admin-videogames/delete
Content-Type: application/json

{
    "_id": "63fe64232925b97464f56305"
}
