# Crear etiqueta RPG
POST http://localhost:3000/admin-tags/post
content-type: application/json

{
    "id": 1,
    "name": "Shooter"
}

######
# Crear etiqueta Shooter
POST http://localhost:3000/admin-tags/post
content-type: application/json

{
    "id": 2,
    "name": "Shooter"
}

######
# Obtener todas las etiquetas
GET http://localhost:3000/admin-tags/get

######
# Obtener la etiqueta 1
GET http://localhost:3000/admin-tags/get/1

######
# Obtener el mayor id
GET http://localhost:3000/admin-tags/getMaxId


######
# Actualizar la etiqueta 1
PUT http://localhost:3000/admin-tags/put/2
Content-Type: application/json

{
  "name": "Adventure"
}

######
# Eliminar la etiqueta 1
DELETE http://localhost:3000/admin-tags/delete/2


######
# Obtener cantidad de videojuegos con solo la etiqueta dad
GET http://localhost:3000/admin-videogames/get-only-specific-tag-count/2
    

####

#Subir Videojuego
POST http://localhost:3000/admin-videogames/post
Content-Type: application/json

{
    "titulo": "WednesdayWithFile8",
    "sinopsis": "Niam despierta en un cuarto, pero hay algo extraño. Esta es la casa en la que vivía hace 37 años, cuando era sólo un niño. Ahora para volver al futuro tendrá que obtener ayuda de un niño, quien es el que tiene las herramientas para abrir los portales que lo llevarán de regreso al presente. ",
    "usuario": "a",
    "imagepath": "C:\\Excalinest\\img\\portada2.png",
    "filepath": "C:\\Excalinest\\builds\\file.zip",
    "facepath": "C:\\Excalinest\\img\\Keane.png",
    "instapath": "C:\\Excalinest\\img\\Crumb.png",
    "twitterpath": "C:\\Excalinest\\img\\Palace.png",
    "tags": [{"id": 2, "name": "Shooter"}]
}

####

#Actualizar Videojuego
PUT http://localhost:3000/admin-videogames/put
Content-Type: application/json

{
    "_id": "6413646074f47ac27cedc74b",
    "sinopsis": "Sinopsis del videojuego",
    "usuario": ""
}

####

#Get videojuego
GET http://localhost:3000/admin-videogames/get

####

#Borrar videojuego
DELETE http://localhost:3000/admin-videogames/delete
Content-Type: application/json

{
    "_id": "64166d1cb6de4ba4bdaeb8fc"
}


####

# Obtener zip

GET http://localhost:3000/admin-videogames/get-zip-file
Content-Type: application/json

{
    "filename": "Mirror.zip",
    "destPath": "C:\\Users\\Silvia Rodríguez\\Desktop\\Juego\\Descarga\\"
}