name: Deploy Excalinest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Deploy frontend and backend to Oracle Cloud Canonical Ubuntu 22.04 Instance
        run: |
          echo "$ORACLE_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key ubuntu@140.84.188.161 "sudo systemctl stop apache2"
        env:
          ORACLE_SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
