name: Deploy Excalinest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-to-test-if-this-info-works'

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.IP_PUBLICA }} >> ~/.ssh/known_hosts

      - name: Adding public key to authorized_keys
        run: |
          echo "$ORACLE_SSH_PUBLIC_KEY" >> authorized_keys
          chmod 600 authorized_keys
          chmod 700 ~/.ssh
          cat authorized_keys >> ~/.ssh/authorized_keys
        
      - name: Deploy frontend and backend to Oracle Cloud CentOS Stream 8 Instance
        run: |
          echo "$ORACLE_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          echo "$SSH_CREDENTIALS" > ssh_credentials
          chmod 600 ssh_credentials
          chmod 0 ./Frontend/Excalinest/dist/coreui-free-angular-admin-template/
          sudo rsync -e "ssh -i private_key" -r --delete-after ./Frontend/Excalinest/dist/coreui-free-angular-admin-template/ $(cat ssh_credentials):/var/www/html/
        env:
          ORACLE_SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          SSH_CREDENTIALS: ${{ secrets.SSH_CREDENTIALS }}
