name: Deploy Excalinest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-to-test-if-this-info-works'

      - name: Adding Known Hosts and authorized keys
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.IP_PUBLICA }} >> ~/.ssh/known_hosts
          cat ${{ secrets.ORACLE_SSH_PUBLIC_KEY }} >> ~/.ssh/authorized_keys

      - name: Deploy frontend and backend to Oracle Cloud CentOS Stream 8 Instance
        run: |
          ssh -i ${{ secrets.ORACLE_SSH_PRIVATE_KEY }} ${{ secrets.SSH_CREDENTIALS }} "sudo systemctl stop apache2"
