name: Deploy Excalinest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-to-test-if-this-info-works'

      - name: Adding Known Hosts  
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.IP_PUBLICA }} >> ~/.ssh/known_hosts

      - name: Deploy frontend and backend to Oracle Cloud Canonical Ubuntu 22.04 Instance
        run: |
          echo "${{ secrets.ORACLE_SSH_PRIVATE_KEY }}" > private_key
          echo "${{ secrets.SSH_CREDENTIALS }}" > ssh_credentials
          chmod 600 private_key
          chmod 600 ssh_credentials
          ssh -i private_key ssh_credentials "sudo systemctl stop apache2"
