name: Deploy Excalinest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-to-test-if-this-info-works'

      - name: Adding Known Hosts  
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 140.84.188.161 >> ~/.ssh/known_hosts

      - name: Deploy frontend and backend to Oracle Cloud Canonical Ubuntu 22.04 Instance
        run: |
          echo "$ORACLE_SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key ubuntu@140.84.188.161 "sudo systemctl stop apache2"
        env:
          ORACLE_SSH_PRIVATE_KEY: ${{ secrets.ORACLE_SSH_PRIVATE_KEY }}
